# Generated by Django 5.0.6 on 2024-07-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_app', '0002_item_description_item_photo_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
    ]
